### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by balagab** [themondays/redmine_worktime_log#1]
Hi there!

This is a cool plugin, but I have some problem:
1. don't see the spent time on issue's site, I ran the timer for more than 1m, but the spent time field is still blank.
2. when start the timer, there is a "select an option", but there is no value. I can't choose.
3. Is it possible to regulate it? A user should run the timer only if the issue is assigned him/her.

Thanks,
Gabor

**Comment by themondays** [comment]
Hey Gabor,
Possible you have to raise more steps:
1. Ensure that you have projects
2. Ensure that you have issues inside projects (of course man you have some :)
3. Assign yourself to issue.
Check dropdown inside widget.

I'm afraid that you may catch another errors during time calculation (because of some difference between my dev database and your), just let me know if something new will appear.

Thanks,
Jared.

**Comment by balagab** [comment]
Hi Jared,
1. ok
2. ok
3. not ok :) didn't know it is a condition but it's great, like. :)

I thought I should see the spent time in "spent time" original field, but I can see the text "You spent: 00:01:15 Total: 00:01:15 Snap Up Start" I can clik start/stop in this text, but if I click "snap up" I get internal error, Please find below the production log relevant part:

"Started GET "/worktime/stopwatch/snapup/1?back=true" for 192.168.10.139 at 2015-01-28 10:48:55 +0000
Processing by StopwatchController#snapup as HTML
  Parameters: {"back"=>"true", "id"=>"1"}
  Current user: user (id=1)
Completed 500 Internal Server Error in 3.6ms

NoMethodError (undefined method `[]' for nil:NilClass):
  plugins/redmine_worktime_log/app/controllers/stopwatch_controller.rb:67:in`_stop'
  plugins/redmine_worktime_log/app/controllers/stopwatch_controller.rb:107:in `snapup'
  actionpack (3.2.19) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
  actionpack (3.2.19) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.19) lib/action_controller/metal/rendering.rb:10:in`process_action'
  actionpack (3.2.19) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.19) lib/active_support/callbacks.rb:469:in`_run__1670847483639279309__process_action__1683660794938541947__callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.19) lib/active_support/callbacks.rb:385:in`_run_process_action_callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.19) lib/abstract_controller/callbacks.rb:17:in`process_action'
  actionpack (3.2.19) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.19) lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
  activesupport (3.2.19) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.19) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (3.2.19) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.19) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
  actionpack (3.2.19) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.19) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  actionpack (3.2.19) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.19) lib/abstract_controller/rendering.rb:45:in`process'
  actionpack (3.2.19) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.19) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
  actionpack (3.2.19) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:73:in`call'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:36:in`call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in`each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:608:in`call'
  rack-openid (1.4.1) lib/rack/openid.rb:99:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in`call'
  actionpack (3.2.19) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
  actionpack (3.2.19) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in`context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/cookies.rb:341:in`call'
  activerecord (3.2.19) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.19) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in`call'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in`_run__214762095665948061__call__121289310774066534__callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.19) lib/active_support/callbacks.rb:385:in`_run_call_callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
  actionpack (3.2.19) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
  actionpack (3.2.19) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.19) lib/rails/rack/logger.rb:32:in`call_app'
  railties (3.2.19) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.19) lib/active_support/tagged_logging.rb:22:in`tagged'
  railties (3.2.19) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/request_id.rb:22:in`call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in`call'
  activesupport (3.2.19) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in`call'
  actionpack (3.2.19) lib/action_dispatch/middleware/static.rb:63:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.19) lib/rails/engine.rb:484:in `call'
  railties (3.2.19) lib/rails/application.rb:231:in`call'
  railties (3.2.19) lib/rails/railtie/configurable.rb:30:in `method_missing'
  rack (1.4.5) lib/rack/builder.rb:134:in`call'
  rack (1.4.5) lib/rack/urlmap.rb:64:in `block in call'
  rack (1.4.5) lib/rack/urlmap.rb:49:in`each'
  rack (1.4.5) lib/rack/urlmap.rb:49:in `call'
  passenger (4.0.45) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in`process_request'
  passenger (4.0.45) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  passenger (4.0.45) lib/phusion_passenger/request_handler/thread_handler.rb:109:in`main_loop'
  passenger (4.0.45) lib/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'"

Thanks,
Gabor

**Comment by themondays** [comment]
Will check it shortly. Btw I have added new candidate here, you may try it. There also one fix for snap up query.

**Comment by themondays** [comment]
And yeah, I have plans to update spent hours inside entire ticket in next releases but not right now :-1:

**Comment by balagab** [comment]
Hi, is it normal that I can see the spent time on my summary, but not on the issue's page in "spent time" field. :(
Evereything else is great! Thank you.

**Comment by balagab** [comment]
It would be great if the spent time field would show the time, because we have a lot of queries for that field.
